
# Dit bestand is in toml-formaat
# Zie: https://github.com/mojombo/toml

port = 9876
url  = "http://paqu.domain.nl:9876/"

default = "lassysmall"

mailfrom = "maintainer@domain.nl"
smtpserv = "smtp.domain.nl:25"
smtpuser = ""
smtppass = ""

login  = "username:password@/paqu"
prefix = "pq"

maxjob = 10
maxwrd = 1000000
maxmem = 54098268160

sh     = "/bin/sh"
path   = "/local/opt/paqu/pqbuild:/local/opt/paqu/alpino:/bin:/usr/bin"
alpino = "/local/opt/Alpino"

secret = "Verander dit in een andere willekeurige tekst"
remote = true

querytimeout = 120

directories = [
  "/net/corpora/LassySmall/Treebank",
  "/net/corpora/LassyLarge/NLWIKI20110804/DACT"
]

[[view]]
allow = true
addr  = [ "127.0.0.1/8", "123.123.123.123" ]

[[view]]
allow = false
addr  = [ "all" ]

[[access]]
allow = true
mail  = [ "@xs4all\\.nl$", "@rug\\.nl$" ]  # kleine letters

[[access]]
allow = false
mail  = [ "all" ]

